"""Generates publication-ready genetic locus maps.

This script ingests coordinate TSV files, normalizes coordinates to a
zero-anchor baseline, applies functional color-coding, and exports
high-resolution vector (PDF) and print-ready (300 DPI TIFF) figures.

License: MIT
Reproducibility: Associated with upcoming research (manuscript in preparation).

Example usage:
    $ python3 plot_locus.py -i coords.tsv -o C5_Bacteriocin_Locus
"""

__author__ = "Jan Ephraim R. Vallente"
__email__ = "ephrvallente@gmail.com"
__version__ = "1.0.1"

import sys
import argparse
import matplotlib.pyplot as plt
from pathlib import Path
from dna_features_viewer import GraphicFeature, GraphicRecord

# --- FUNCTIONAL COLOR MAP ---
# Format: (start_gene_num, end_gene_num, hex_color, biological_role)
COLOR_MAP = [
    (46, 48, "#a5d6a7", "Flanking/accessory"),
    (49, 51, "#ef5350", "Immunity/regulation"),
    (52, 64, "#90caf9", "Core biosynthetic"),
    (65, 67, "#ef5350", "Immunity/regulation"),
    (68, 72, "#ce93d8", "Ancestral lactobin"),
    (73, 74, "#ffb74d", "Transport"),
]
COLOR_DEFAULT = "#cccccc"


def setup_cli() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate publication-ready genetic locus maps from TSV coordinates."
    )
    parser.add_argument(
        "-i",
        "--input",
        type=Path,
        required=True,
        help="Input TSV file generated by get_coordinates.py",
    )
    parser.add_argument(
        "-o",
        "--output",
        type=str,
        required=True,
        help="Prefix for output image files (e.g., 'C5_SuperLocus')",
    )
    return parser.parse_args()


def main() -> None:
    args = setup_cli()
    raw_features = []

    try:
        with open(args.input, "r", encoding="utf-8") as f:
            header = f.readline()
            for line in f:
                if not line.strip():
                    continue
                parts = line.strip().split("\t")
                locus_tag, start_str, end_str, strand_str, product = parts

                # Robustly extract the gene number to assign colors
                digit_str = "".join(filter(str.isdigit, locus_tag))
                gene_num = int(digit_str) if digit_str else 0

                assigned_color = COLOR_DEFAULT
                for start_bound, end_bound, hex_color, role in COLOR_MAP:
                    if start_bound <= gene_num <= end_bound:
                        assigned_color = hex_color
                        break

                raw_features.append(
                    {
                        "start": int(start_str),
                        "end": int(end_str),
                        "strand": int(strand_str),
                        "label": f"{locus_tag.split('_')[-1]}",  # Shortened label for clean plotting
                        "color": assigned_color,
                    }
                )
    except FileNotFoundError:
        sys.exit(f"[!] File not found: {args.input}")
    except Exception as e:
        sys.exit(f"[!] Error parsing TSV: {e}")

    if not raw_features:
        sys.exit("[!] Error: No features found to plot.")

    # Dynamic Zero-Anchor
    anchor = min(f["start"] for f in raw_features)

    normalized_features = [
        GraphicFeature(
            start=f["start"] - anchor,
            end=f["end"] - anchor,
            strand=f["strand"],
            label=f["label"],
            color=f["color"],
        )
        for f in raw_features
    ]

    total_span = max(f.end for f in normalized_features)
    record = GraphicRecord(sequence_length=total_span, features=normalized_features)

    # Plotting
    ax, _ = record.plot(figure_width=16)
    pdf_name = f"{args.output}.pdf"
    tiff_name = f"{args.output}.tiff"

    try:
        ax.figure.savefig(pdf_name, bbox_inches="tight")
        ax.figure.savefig(tiff_name, format="tiff", dpi=300, bbox_inches="tight")
        print(f"\n[✓] Normalized locus matrix anchored at: -{anchor} bp.")
        print(f"[✓] Total architecture scale length: {total_span} bp.")
        print(f"[✓] Figures generated successfully:")
        print(f"    -> {pdf_name}")
        print(f"    -> {tiff_name}")
    except OSError as e:
        sys.exit(f"\n[!] Error saving figures: {e}")
    finally:
        plt.close(ax.figure)


if __name__ == "__main__":
    main()
